### ISSUE TITLE
USER STORY <Title>

### ISSUE THREAD

**Issue by 0DylanMcMahon** [DylanP400/love-running#4]
As a **Member** I  would like to  **Sign-up** so that **I can have an account with Love running**

# Acceptance Criteria

  * Acceptance Criteria 1: Have the option to sign up
  * Acceptance Criteria 2: Add a login button in the header
  * Acceptance Criteria 3: Add a sign-up button.
  * Acceptance Criteria 4:  Add a remember me checkbox

# Tasks

- [ ]  Task 1: Create the Html.
- [ ]  Task 2: create the css.
- [ ]  Task 3: Do the backend.
